# Generated by Django 3.1.1 on 2021-01-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201230_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine_classification',
            name='author',
        ),
    ]
